name: Eatery Prod Server - CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup environment variables
        run: echo "${{ secrets.ENV_PROPERTIES }}" > ./src/main/resources/env.properties

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Docker build and push
        if: ${{ !failure() }}
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }} --platform linux/arm64 .
          docker push ${{ secrets.DOCKER_REPO }}

      - name: Executing remote ssh commands with docker compose for Continuous Delivery
        if: ${{ !failure() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          key: ${{ secrets.AWS_EC2_KEY }}
          username: ec2-user
          script: |
            cd /home/ec2-user/hertz
            docker-compose down
            docker-compose pull
            docker-compose up -d

      - name: Upload Jacoco Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html